pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
              sh 'cd my-app && mvn test'
            }
        }
        stage('Test'){
            steps{
          		echo 'hello from myapp'
            }
        }
        stage('Publish'){
            steps {
               echo 'great success'
            }
        }
    }
}
